services:
  - type: web
    name: aaroh-backend
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip ffmpeg
      pip3 install librosa numpy soundfile
      npm install
    startCommand: node server/server.js
    envVars:
      - key: MONGO_URI
        value: your_mongo_uri_here
      - key: JWT_SECRET
        value: your_jwt_secret_here
    plan: free
    region: oregon
